Local wisper
StanGirard/quivr pull request #1091
Opened 2023-09-01 13:23 UTC by aadityamundhalia

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context.

## Checklist before requesting a review

Please delete options that are not relevant.

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented hard-to-understand areas
- [X] I have ideally added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes -> was not able to to run the tests locally sorry I am not python programmer so got bit limited knowledge
- [X] Any dependent changes have been merged

## Video (if appropriate):

https://github.com/StanGirard/quivr/assets/857107/af9e19cc-4cc6-48a0-b39d-2deb266a2d1c

2023-09-04 07:12 UTC, StanGirard requested changes

2023-09-04 07:12 UTC, StanGirard commented on .backend_env.example
> +WISPER_LOCAL=True
WHISPER with an H ?

2023-09-04 07:12 UTC, StanGirard commented on backend/parsers/wisper.py
Rename to whisper with an h

2023-09-04 07:12 UTC, StanGirard commented on backend/tests/test_files/video.mp4
What is this video ?

2023-09-04 07:12 UTC, StanGirard commented on backend/utils/processors.py
Same whisper with an H :)

2023-09-04 07:12 UTC, StanGirard commented on backend/parsers/wisper.py
Instead of creating a new file that does exactly the same things. Can you merge this with the existing whisper audio and video and just change the place where the transcribing either local or online ? 

That avoids code duplication and if then else it the process_files array

2023-09-04 08:46 UTC, aadityamundhalia commented on backend/tests/test_files/video.mp4
some random video I download to test the transcript

2023-09-04 08:49 UTC, aadityamundhalia commented on backend/parsers/wisper.py
I made the change because I wanted to separate the openai version vs the local version. I originally thought abut that but the amount if were looking good so created a new class, I will merge them no worries.

2023-09-04 08:50 UTC, jameslacia commented on .backend_env.example
> +WISPER_LOCAL=True
may I complain with you sir......

2023-09-04 08:52 UTC, jameslacia commented on backend/parsers/wisper.py
I didn't expect in this message are not - complain without knowledge........

2023-09-04 08:52 UTC, gozineb commented on backend/parsers/common.py
> +    # add_usage(stats_db, "embedding", "audio", metadata={"file_name": file_meta_name,"file_type": ".txt", "chunk_size": chunk_size, "chunk_overlap": chunk_overlap})
Remove irrelevant comment

2023-09-04 08:54 UTC, jameslacia commented
we are anonymous we are legion we do not forgive we do not forget expect
us.

On Mon, Sep 4, 2023, 16:47 Aditya Mundhalia ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> On backend/tests/test_files/video.mp4
> <https://github.com/StanGirard/quivr/pull/1091#discussion_r1314628361>:
>
> some random video I download to test the transcript
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/StanGirard/quivr/pull/1091#discussion_r1314628361>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A6XP5BRYDN5W4ECWSYB3TFLXYWIRNANCNFSM6AAAAAA4HSHD6U>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2023-09-07 11:12 UTC, gozineb commented
Hi @aadityamundhalia, just tested it locally and had the following error while upload the mp4 in the test files:
<img width="1097" alt="Screenshot 2023-09-07 at 13 09 43" src="https://github.com/StanGirard/quivr/assets/100568984/7688368d-ce7d-4d83-a42d-bcfaa12b28ed">

Can you please take a look at it ?

2023-09-07 11:15 UTC, aadityamundhalia commented
@gozineb can you please share your .env file.
also you need to rebuild the containers so try:
```bash
docker-compose down
docker-compose -f docker-compose.dev.gpu.yml up -d --build
```

I will re run on my local to confirm

2023-09-07 11:31 UTC, gozineb commented
I have updated my .env in the backend with LOCAL_WHISPER=True.
I have tested the make dev and the make prod which are used respectively in local and in prod. They should still be able to work after your changes.
Also, with `docker-compose -f docker-compose.dev.gpu.yml up -d --build`, i get the following error:
<img width="1097" alt="Screenshot 2023-09-07 at 13 31 11" src="https://github.com/StanGirard/quivr/assets/100568984/22581819-82b7-46c4-b02e-7fc0a2760acd">

2023-09-07 12:32 UTC, aadityamundhalia commented
@gozineb my apologies I did tested after my changes looks like it did no load the latest at that time. When retried was able to replicated the issue there was a small issue with the quotes that is now resolved. I will appreciate if you can have another go thanks

2023-09-07 12:32 UTC, StanGirard commented
Thé issue might be that you don't have a gpu and therefore cannot test.

2023-09-07 12:39 UTC, aadityamundhalia commented
@StanGirard this will work on cpu as well just bit slow but will work tried on my 12900k was no issues. There was an issue with my if statement that is now resolved. Try again please it should work

2023-09-07 13:05 UTC, gozineb commented
@aadityamundhalia seems to be working now for make dev !!  Still same issue with make prod though : `Error processing file: cannot use a string pattern on a bytes-like object`

And still getting the same error with the docker-compose -f docker-compose.dev.gpu.yml up -d --build

2023-09-07 15:32 UTC, aadityamundhalia commented
@gozineb you can't run the gpu yml on Mac as Mac don't have gpu

2023-09-11 13:24 UTC, gozineb commented
Sorry @aadityamundhalia, still not working for me:  `Error processing file: cannot use a string pattern on a bytes-like object.` Don't think it has anything to do with the gpu/MAC

2023-09-13 00:05 UTC, aadityamundhalia commented
@gozineb I will try to create a step by step by step document for how to get it working will also try to run it on my m1 mac to see if there are any issues.

2023-10-01 11:27 UTC, aadityamundhalia commented
@gozineb Sorry for late reply, I have not forgotten about this. Just bit occupied these days. So far I have learned that local wisper do not work on m1 mac.

2023-10-27 09:37 UTC, mamadoudicko commented
Closing since it has been a while. Feel free to re-open it when you'll be available @aadityamundhalia

2023-10-27 09:38 UTC, closed without merging