analytics(google): add google analytics
StanGirard/quivr pull request #1147
Opened 2023-09-11 14:51 UTC by gozineb

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context.

## Checklist before requesting a review

Please delete options that are not relevant.

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented hard-to-understand areas
- [ ] I have ideally added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged

## Screenshots (if appropriate):

2023-09-11 16:07 UTC, StanGirard submitted a review, later dismissed
LGTM

2023-09-12 06:59 UTC, StanGirard commented
@gozineb don't you need to add Google analytics to SCP ?

2023-09-12 13:04 UTC, StanGirard requested changes

2023-09-12 13:04 UTC, StanGirard commented on frontend/app/user/components/ApiKeyConfig/hooks/useApiKeyConfig.ts
> +  const gaEventTracker = useGAnalyticsEventTracker("QUIVR_API_KEY");
@gozineb what is that ?

2023-09-12 13:04 UTC, StanGirard commented on frontend/app/user/components/ApiKeyConfig/hooks/useApiKeyConfig.ts
> +  const gaEventTracker = useGAnalyticsEventTracker("QUIVR_API_KEY");
It is not declared

2023-09-14 10:38 UTC, mamadoudicko commented on frontend/app/user/components/ApiKeyConfig/hooks/useApiKeyConfig.ts
> +  const gaEventTracker = useGAnalyticsEventTracker("QUIVR_API_KEY");
Maybe 
```ts
  const {trackEvent } = useGAnalyticsEventTracker({
    eventsCategory: "QUIVR_API_KEY",
  })
```

2023-09-14 10:38 UTC, mamadoudicko commented on frontend/services/analytics/google/googleAnalytics.tsx
> +};
Seems to be a duplication. Already done in `ReactGA.initialize(ga_id)` in `useGAnalyticsEventTracker`

2023-09-14 10:40 UTC, mamadoudicko commented
Some frontend tests need to be updated: Vitest step is falling

2023-09-18 13:01 UTC, mamadoudicko submitted a review, later dismissed

2023-09-18 13:09 UTC, StanGirard approved these changes

2023-09-18 13:12 UTC, merged