Feat/model config
StanGirard/quivr pull request #223
Opened 2023-05-31 20:29 UTC by mamadoudicko

# Description

In this PR, we add brain config page to Quivr

## Checklist before requesting a review

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented hard-to-understand areas
- [x
<img width="1504" alt="Screenshot 2023-05-31 at 22 28 03" src="https://github.com/StanGirard/quivr/assets/63923024/5a6338bf-2acb-4163-a0f3-3a070695c079">
] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

## Screenshots (if appropriate):

2023-06-01 05:12 UTC, iMADi-ARCH requested changes
Awesome PR @mamadoudicko 😄
The `useAxios` hook is top notch 👌🏼. 
Once again, loving the modularity. 💯

2023-06-01 05:12 UTC, iMADi-ARCH commented on frontend/app/explore/DocumentItem/DocumentData.tsx
This will probably break as hooks cannot be used in server components. 
A possible fix would be to convert this to a client component and fetch the data in `useEffect`.

(This is the only server component in this whole project so better if we opt out of using server components as probably there are plans for a desktop application.)

2023-06-02 10:23 UTC, StanGirard commented
@mamadoudicko it seems that the issue 422 comes from the frontend side

2023-06-02 11:35 UTC, mamadoudicko commented on frontend/app/explore/DocumentItem/DocumentData.tsx
Oh yes ! Thanks @iMADi-ARCH 

Update: no longer a server component

2023-06-02 15:01 UTC, merged